name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag renti_frontend-name:v1

    - name: Run a docker container from the image
      run: docker run --name Renti -p 3000:3000 renti_frontend-name:v1

    - name: Test the deployment
      run: curl http://localhost:3000 | grep React

    - name : Terminate the docker Container
      run: docker stop Renti

  
